analysis/backend/urls.py
"""
This file is part of UTAP.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.conf.urls import url

from analysis.backend.views import views_general as general_views
from analysis.backend.views.views_analysis_atacseq import AnalysisAtacSeqView
from analysis.backend.views.views_analysis_chipseq import AnalysisChipSeqView
from analysis.backend.views.views_analysis_riboseq import AnalysisRiboSeqView
from analysis.backend.views.views_analysis_deseq_to_counts_matrix import AnalysisDESeqFromCountsMatrixView
from analysis.backend.views.views_analysis_demultiplexing import AnalysisDemultiplexingView
from analysis.backend.views.views_analysis_singlecell import AnalysisSinglecellView
from analysis.backend.views.views_analysis_submit import AnalysisSubmitView
from analysis.backend.views.views_analysis_transcriptome import AnalysisTranscriptomeView, AnalysisDeseqView

app_name = 'analysis'
from analysis.backend.views.views_general import AnalysisChoice, LoginAsUser, samples_list_ajax, AnalysisDetailsView, \
    remote_samples_list_ajax, UserDatasets, no_results, run_failed, demultiplexing_results, temp, test, \
    stest, folder_exists_ajax, has_space_on_disc_ajax, signup, activate_user, \
    UploadFolder, upload_progress, upload_help, DeleteAnalysisView, analysis_progress_ajax, Elearning, atacseq_results, chipseq_results, check_samplesheet_ajax

urlpatterns = [
    url(r'^signup/$', signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate_user,
        name='activate'),
    url(r'^login_as/$', LoginAsUser.as_view(), name='login_as'),
    url(r'^user_logout/$', general_views.logout_view, name='user_logout'),
    url(r'^ajax/samples_list/$', samples_list_ajax, name='samples_list'),
    url(r'^ajax/folder_exists/$', folder_exists_ajax, name='folder_exists'),
    url(r'^ajax/free_space/$', has_space_on_disc_ajax, name='free_space'),
    url(r'^ajax/remote_samples_list/$', remote_samples_list_ajax, name='remote_samples_list'),
    url(r'^ajax/check_samplesheet/$', check_samplesheet_ajax, name='check_samplesheet'),
    url(r'^run_deseq/(?P<pipeline>.*)/$', AnalysisDeseqView.as_view(), name='run_deseq'),
    url(r'^ajax/delete_analysis/$', DeleteAnalysisView.as_view(), name='delete_analysis'),
    url(r'^analysis_details/(?P<pk>[0-9]+)/$', AnalysisDetailsView.as_view(), name='analysis_details'),
    url(r'^e_learning/$', Elearning.as_view(), name='e_learning'),
    url(r'^user_datasets/$', UserDatasets.as_view(), name='user_datasets'),
    url(r'^chanalysis/$', AnalysisChoice.as_view(), name='choice_analysis'),
    url(r'^analysis/(?P<pipeline>Transcriptome.*)/$', AnalysisTranscriptomeView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>Demultiplexing.*)/$', AnalysisDemultiplexingView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>Single-cell RNA Cell Ranger.*)/$', AnalysisSinglecellView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>ATAC-Seq.*)/$', AnalysisAtacSeqView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>ChIP-Seq.*)/$', AnalysisChipSeqView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>Ribo-Seq.*)/$', AnalysisRiboSeqView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>DESeq2.*)/$', AnalysisDESeqFromCountsMatrixView.as_view(), name='analysis'),
    url(r'^submit_analysis/(?P<pipeline>.*)/$', AnalysisSubmitView.as_view(), name='submit_analysis'),
    url(r'^temp/$', temp, name='temp'),
    url(r'^test/$', test, name='test'),
    url(r'^stest/$', stest, name='stest'),
    url(r'^upload_help/$', upload_help, name='upload_help'),
    url(r'^no_results/$', no_results, name='no_resutls'),
    url(r'^run_failed/$', run_failed, name=''),
    url(r'^demultiplexing_results/$', demultiplexing_results, name='demultiplexing_results'),
    url(r'^atacseq_results/$', atacseq_results, name='atacseq_results'),
    url(r'^chipseq_results/$', chipseq_results, name='chipseq_results'),
    #url(r'^$', UserDatasets.as_view(), name='user_datasets'),
    url(r'^$', Elearning.as_view(), name='e_learning'),
    url(r'^upfolder/$', UploadFolder.as_view(), name='upfolder'),
    url(r'^upload_progress/$', upload_progress, name="upload-progress"),
    url(r'^ajax/analysis_progress/$', analysis_progress_ajax.as_view(), name="analysis_progress"),
]

utap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views
from filebrowser.sites import site

from analysis.backend.forms.forms_base import LoginForm
from analysis.backend.settings import BBCU_INTERNAL, INSTITUTE_NAME, DEMO_SITE, UTAP_VERSION

urlpatterns = [
    url(r'', include('analysis.backend.urls')),
    url('^', include('django.contrib.auth.urls')),
    # url(r'^flowjs/', include('flowjs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},
        name='login'),
    url(r'^user_login/$', views.login,
        {'template_name': 'login.html', 'extra_context': {'bbcu_internal': BBCU_INTERNAL, 'institute_name': INSTITUTE_NAME, 'demosite': DEMO_SITE, 'version': UTAP_VERSION}}, name='user_login'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
]

analysis/backend/forms/forms_singlecell.py
"""
This file is part of UTAP.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
"""

import logging

from django import forms
from django.utils.translation import ugettext_lazy as _

from analysis.backend.forms.forms_base import AnalysisBaseForm
from analysis.backend.utils.consts import BASIC_ID
from analysis.models import SinglecellAnalysis

logger = logging.getLogger(__name__)


class SinglecellForm(AnalysisBaseForm):
    def __init__(self, user_name, *args, **kwargs):
        super(SinglecellForm, self).__init__(user_name, *args, **kwargs)
        # FileBrowseField override the help_text from Meta class
        self.fields['input_folder'].help_text = _(
            'Folder with fastq files in appropriate structure (see help for details).')
        self.fields['input_folder'].widget.attrs = {'class': 'btn btn-default', 'form_id': BASIC_ID}
        self.fields['input_folder'].required = True  # blank=true don't work in FileBrowseField

    class Meta(AnalysisBaseForm.Meta):
        model = SinglecellAnalysis
        fields = ['name', 'pipeline', 'input_folder', 'cellranger_genome', 'output_folder', 'email']
        AnalysisBaseForm.Meta.widgets['cellranger_genome'] = forms.Select(attrs={'class': 'btn btn-default', 'form_id': BASIC_ID})


analysis/backend/views/views_analysis_atacseq.py
"""
This file is part of UTAP.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
"""

import abc
import logging

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from analysis.backend.forms.forms_atacseq import AtacSeqForm
from analysis.backend.run.run_ngs_atacseq import RunAtacSeq
from analysis.backend.utils.consts import FUTURE_DATA_TYPE, ATACSEQ_ANALYSIS_TYPE
from analysis.backend.views.views_analysis_base import AnalysisBaseView
from analysis.backend.views.views_general import LoginAsUser

logger = logging.getLogger(__name__)


# csrf_exempt cancel the need for csrf in the login. For enabling to login with python code
@method_decorator(csrf_exempt, name='dispatch')
@method_decorator(login_required(login_url="/user_login/"), name='dispatch')
class AnalysisAtacSeqView(AnalysisBaseView):
    @abc.abstractmethod
    def get_form_class(self, pipeline):
        if pipeline == ATACSEQ_ANALYSIS_TYPE:
            return AtacSeqForm
        elif pipeline == FUTURE_DATA_TYPE:  # template for future analyses
            return 'FutureForm'

    @abc.abstractmethod
    def get_analysis_class(self, pipeline):
        if pipeline == ATACSEQ_ANALYSIS_TYPE:
            return RunAtacSeq
        elif pipeline == FUTURE_DATA_TYPE:  # template for future analyses
            return 'FutureForm'

    @abc.abstractmethod
    def check_validation_specific_to_pipeline(self, analysis_form, request):
        self.check_validation(analysis_form, request, 'input_folder')

    @abc.abstractmethod
    def save_to_model_specific_to_pipeline(self, pipeline, analysis_form, request):
        # if output_dir is empty, the output folder created in run function with name and date.
        self.output_dir_ = None

    def post(self, request, pipeline, *args, **kwargs):
        if 'user' in request.GET.keys():  # submit user post analyses with user argument
            username = request.GET['user']
            LoginAsUser().login_as_user(username, request)
        return super(AnalysisAtacSeqView, self).post(request, pipeline, *args, **kwargs)

analysis/backend/views/views_analysis_chipseq.py
"""
This file is part of UTAP.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
"""

import abc
import logging

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from analysis.backend.forms.forms_chipseq import ChipSeqForm
from analysis.backend.run.run_ngs_chipseq import RunChipSeq
from analysis.backend.utils.consts import FUTURE_DATA_TYPE, CHIPSEQ_ANALYSIS_TYPE
from analysis.backend.views.views_analysis_base import AnalysisBaseView
from analysis.backend.views.views_general import LoginAsUser

logger = logging.getLogger(__name__)


# csrf_exempt cancel the need for csrf in the login. For enabling to login with python code
@method_decorator(csrf_exempt, name='dispatch')
@method_decorator(login_required(login_url="/user_login/"), name='dispatch')
class AnalysisChipSeqView(AnalysisBaseView):
    @abc.abstractmethod
    def get_form_class(self, pipeline):
        if pipeline == CHIPSEQ_ANALYSIS_TYPE:
            return ChipSeqForm
        elif pipeline == FUTURE_DATA_TYPE:  # template for future analyses
            return 'FutureForm'

    @abc.abstractmethod
    def get_analysis_class(self, pipeline):
        if pipeline == CHIPSEQ_ANALYSIS_TYPE:
            return RunChipSeq
        elif pipeline == FUTURE_DATA_TYPE:  # template for future analyses
            return 'FutureForm'

    @abc.abstractmethod
    def check_validation_specific_to_pipeline(self, analysis_form, request):
        self.check_validation(analysis_form, request, 'input_folder')

    @abc.abstractmethod
    def save_to_model_specific_to_pipeline(self, pipeline, analysis_form, request):
        # if output_dir is empty, the output folder created in run function with name and date.
        self.output_dir_ = None

    def post(self, request, pipeline, *args, **kwargs):
        if 'user' in request.GET.keys():  # submit user post analyses with user argument
            username = request.GET['user']
            LoginAsUser().login_as_user(username, request)
        return super(AnalysisChipSeqView, self).post(request, pipeline, *args, **kwargs)

analysis/backend/views/views_analysis_demultiplexing.py
"""
This file is part of UTAP.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
"""

import abc
import logging

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from analysis.backend.forms.forms_demultiplexing import DemultiplexingFastqForm, DemultiplexingRunidForm, \
    DemultiplexingBclForm
from analysis.backend.run.run_demultiplexing import RunDemultiplexingRunid, RunDemultiplexingBcl, RunDemultiplexingFastq
from analysis.backend.utils.consts import DEMULTIPLEXING_RUNID_ANALYSIS_TYPE, DEMULTIPLEXING_FASTQ_ANALYSIS_TYPE, \
    DEMULTIPLEXING_BCL_ANALYSIS_TYPE, FUTURE_DATA_TYPE
from analysis.backend.views.views_analysis_base import AnalysisBaseView

logger = logging.getLogger(__name__)


# csrf_exempt cancel the need for csrf in the login. For enabling to login with python code
@method_decorator(csrf_exempt, name='dispatch')
@method_decorator(login_required(login_url="/user_login/"), name='dispatch')
class AnalysisDemultiplexingView(AnalysisBaseView):
    @abc.abstractmethod
    def get_form_class(self, pipeline):
        if pipeline == DEMULTIPLEXING_RUNID_ANALYSIS_TYPE:
            return DemultiplexingRunidForm
        if pipeline == DEMULTIPLEXING_FASTQ_ANALYSIS_TYPE:
            return DemultiplexingFastqForm
        if pipeline == DEMULTIPLEXING_BCL_ANALYSIS_TYPE:
            return DemultiplexingBclForm
        elif pipeline == FUTURE_DATA_TYPE:  # template for future analyses
            return 'FutureForm'

    @abc.abstractmethod
    def get_analysis_class(self, pipeline):
        if pipeline == DEMULTIPLEXING_RUNID_ANALYSIS_TYPE:
            return RunDemultiplexingRunid
        if pipeline == DEMULTIPLEXING_FASTQ_ANALYSIS_TYPE:
            return RunDemultiplexingFastq
        if pipeline == DEMULTIPLEXING_BCL_ANALYSIS_TYPE:
            return RunDemultiplexingBcl
        elif pipeline == FUTURE_DATA_TYPE:  # template for future analyses
            return 'FutureForm'

    @abc.abstractmethod
    def save_to_model_specific_to_pipeline(self, pipeline, analysis_form, request):
        # if output_dir is empty, the output folder created in run function with name and date.
        self.output_dir_ = None

    @abc.abstractmethod
    def check_validation_specific_to_pipeline(self, analysis_form, request):
        if 'bcl_files' in analysis_form.cleaned_data:
            self.check_validation(analysis_form, request, 'bcl_files')

    def post(self, request, pipeline, *args, **kwargs):
        # FileBrowseField makes the fastq_file_R2 to required. So we set "none" value before is_valid function
        request_updated = request
        if "fastq_file_R2" in request.POST and not request.POST["fastq_file_R2"]:
            request.POST._mutable = True
            request.POST.update({"fastq_file_R2": "none"})
        return super(AnalysisDemultiplexingView, self).post(request, pipeline, *args, **kwargs)

analysis/templates/analysis/account_activation_sent.html
{% include "analysis/navigation_bar.html" with head2="" head3="" %}


<body>
    <div class="container">
        {% autoescape off %}

        Hello {{ user.first_name }} {{ user.last_name }},<br><br>

        Your information has been sent successfully.<br><br>

        In order to complete your registration, please click the confirmation link in the email that we have sent to {{ user.email }}<br><br>

        Please check, whether the email is in the junk folder of your email account, since confirmation mails with backlinks are sometimes classified as spam.

        {% endautoescape %}
    </div>
</body>
</html>


analysis/templates/analysis/atacseq_results.html
{% include "analysis/navigation_bar.html" %}

<div class="container">
    <h1>See results in the output folder</h1>
</div>

analysis/templates/analysis/navigation_bar.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% load static %}

{% if server_port == '8000' %}
    {% if pipeline_server == 'bio.wexac.weizmann.ac.il' %}
        <script>
              if (window.location.href.indexOf("utap2-staging") == -1) {
                window.setTimeout(function() {window.location.assign("https://utap2-staging.wexac.weizmann.ac.il/")},0); }
        </script>
    {% endif %}
    {% if pipeline_server == 'biu.wexac.weizmann.ac.il' %}
        <script>
              if (window.location.href.indexOf("utap-staging") == -1) {
                window.setTimeout(function() {window.location.assign("https://utap-staging.wexac.weizmann.ac.il/")},0); }
        </script>
    {% endif %}
{% else %}
{% if server_port == '7000' %}
    {% if pipeline_server == 'bio.wexac.weizmann.ac.il' %}
        <script>
          if (window.location.href.indexOf("utap2") == -1) {
            window.setTimeout(function() {window.location.assign("https://utap2.wexac.weizmann.ac.il/")},0); }
        </script>
    {% endif %}
    {% if pipeline_server == 'biu.wexac.weizmann.ac.il' %}
        <script>
          if (window.location.href.indexOf("utap") == -1) {
            window.setTimeout(function() {window.location.assign("https://utap.wexac.weizmann.ac.il/")},0); }
        </script>
    {% endif %}
{% endif %}
{% endif %}

<head>
    <title>UTAP - NGS PIPELINES </title>
    <meta charset="utf-8">

    <link rel="stylesheet" type="text/css" href="{% static 'analysis/css/scrolled_table.css' %}"/>
    <link rel="stylesheet" href="{% static 'analysis/css/sticky-footer.css' %}">
    <link rel="stylesheet" href="{% static 'analysis/css/multiselect.css' %}">
    <link rel="stylesheet" href="{% static 'analysis/css/jquery.jexcel.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'analysis/css/drawdrop.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'analysis/css/w3.css' %}" type="text/css">
    <link rel="shortcut icon" type="image/x-icon"  href="{% static 'analysis/images/bbcuLogoIcon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'analysis/js/jquery.jexcel.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/navigation_bar.1.0.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.71/jquery.csv-0.71.min.js"></script>
    <script type="text/javascript" src="{% static 'analysis/js/drawdrop.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/multiselect.js' %}"></script>
    <script type="module" src="{% static 'analysis/js/create-boxes.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/boxes-trascriptome-batches-colors.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/delete-analysis.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.8/interact.min.js"></script>
    <script type="text/javascript" src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
    <script type="text/javascript" src="{% static 'smart-selects/admin/js/chainedm2m.js' %}"></script>
    <script type="text/javascript" src="{% static 'smart-selects/admin/js/bindfields.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/AddFileBrowser.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/FB_CKEditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/FB_FileBrowseField.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/FB_TinyMCE.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/FB_TinyMCEv4.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/fileuploader.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/TinyMCEAdmin.js' %}"></script>
    <script type="text/javascript" src="{% static 'filebrowser/js/TinyMCEv4Admin.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/flow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/ng-flow-standalone.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'analysis/js/analysis_progress.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="pull-left">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'analysis:user_datasets' %}">UTAP - NGS PIPELINES</a>
            </div>
            {% if user.username != 'submit' %}
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'analysis:e_learning' %}">e-learning</a></li>
                <li class="active"><a href="{% url 'analysis:user_datasets' %}">User Datasets</a></li>
                <li class="active"><a href="{% url 'analysis:upfolder' %}">Upload data</a></li>
                <li class="active"><a href="{% url 'analysis:choice_analysis' %}">Run pipeline</a></li>
                {% if demosite %}
                <a href="https://utap.readthedocs.io" class="btn btn-danger navbar-btn" target="_blank">Help</a>
                {% else %}
                <a href="https://bbcunit.atlassian.net/wiki/spaces/BP/pages/2543551665/16.2.22+UTAP+requirements+description+Weizmann+users" class="btn btn-danger navbar-btn" target="_blank">Help</a>
                {% endif %}
            </ul>
            {% endif %}
        </div>


        <div class="pull-right">
            {% if user.loggedas_username and user.is_active %}
                <button class="btn btn-danger navbar-btn" onclick="location.href='{% url 'analysis:user_logout' %}'">{{ user.username}} run as {{ user.loggedas_username }} Logout</button>
            {% else %}
            {% if user.username and user.is_active %}
                <button class="btn btn-danger navbar-btn" onclick="location.href='{% url 'analysis:user_logout' %}'">{{ user.username }} Logout</button>
            {% endif %}
            {% endif %}
            {% if user.username != 'submit' %}
            {% if user.is_superuser %}
                <button class="btn btn-danger navbar-btn" onclick="location.href='{% url 'login' %}'">Admin Site</button>
            {% endif %}
            {% if user.is_superuser %}
                <button class="btn btn-danger navbar-btn" onclick="location.href='{% url 'analysis:login_as' %}'">Run As User</button>
            {% endif %}
            {% endif %}
        </div>
    </div>
</nav>


<!--<div class="alert alert-warning">-->
<!--<strong style="color: red;">Please note that UTAP will be down for maintanance work from 7.3.22 at 18:00 until 8.3.22 at 12:30-->
<!--</strong>-->
<!--</div>-->
<!--<br/>-->
<!--<br/>-->

<div class="container">
    <h1 id="invalid_browser" align="center" style="color:red"></h1>
    <h2>{{ head2 }}</h2>
    <p>{{ head3 }}</p><br>
    <hr>
</div>

<footer class="container-fluid text-center footer navbar-fixed-bottom" style='height: 80px; block;}'>
  <div class="container">
    <div class="text-muted">
        <div class="row">
        Cite - UTAP: User-friendly Transcriptome Analysis Pipeline. Kohen et al. BMC Bioinformatics 2019, 20(1):154(PMID: 30909881)
        </div>

        <div class="row">
            <div class="col-md-2">
                <br><br>UTAP - Version {{ version }}
            </div>
            <div class="col-md-5">
              <img src="{% static 'analysis/images/wis_logo_heb_v1.png' %}">
            </div>
            <div class="col-md-5">
                Developed by <b><a href="mailto:utap@weizmann.ac.il">UTAP team </a></b><br>Bioinformatics unit at Life Sciences Core Facilities (LSCF)<br>Weizmann Institute of Science&nbsp&nbsp&nbsp&nbsp
            </div>
        </div>
    </div>
  </div>
</footer>


</body>
</html>



analysis/templates/analysis/no_results_yet.html
{% include "analysis/navigation_bar.html" %}

<div class="container">
    <h1>The job is running, no results yet.</h1>
</div>

analysis/templates/analysis/run_failed.html
{% include "analysis/navigation_bar.html" %}

<div class="container">
    <h1>The run failed</h1>
</div>

analysis/templates/analysis/singlecell_results.html
{% include "analysis/navigation_bar.html" %}

<div class="container">
    <h1>See results in the output folder</h1>
</div>