analysis/backend/urls.py
"""
This file is part of UTAP.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.conf.urls import url

from analysis.backend.views import views_general as general_views
from analysis.backend.views.views_analysis_atacseq import AnalysisAtacSeqView
from analysis.backend.views.views_analysis_chipseq import AnalysisChipSeqView
from analysis.backend.views.views_analysis_riboseq import AnalysisRiboSeqView
from analysis.backend.views.views_analysis_deseq_to_counts_matrix import AnalysisDESeqFromCountsMatrixView
from analysis.backend.views.views_analysis_demultiplexing import AnalysisDemultiplexingView
from analysis.backend.views.views_analysis_singlecell import AnalysisSinglecellView
from analysis.backend.views.views_analysis_submit import AnalysisSubmitView
from analysis.backend.views.views_analysis_transcriptome import AnalysisTranscriptomeView, AnalysisDeseqView

app_name = 'analysis'
from analysis.backend.views.views_general import AnalysisChoice, LoginAsUser, samples_list_ajax, AnalysisDetailsView, \
    remote_samples_list_ajax, UserDatasets, no_results, run_failed, demultiplexing_results, temp, test, \
    stest, folder_exists_ajax, has_space_on_disc_ajax, signup, activate_user, \
    UploadFolder, upload_progress, upload_help, DeleteAnalysisView, analysis_progress_ajax, Elearning, atacseq_results, chipseq_results, check_samplesheet_ajax

urlpatterns = [
    url(r'^signup/$', signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate_user,
        name='activate'),
    url(r'^login_as/$', LoginAsUser.as_view(), name='login_as'),
    url(r'^user_logout/$', general_views.logout_view, name='user_logout'),
    url(r'^ajax/samples_list/$', samples_list_ajax, name='samples_list'),
    url(r'^ajax/folder_exists/$', folder_exists_ajax, name='folder_exists'),
    url(r'^ajax/free_space/$', has_space_on_disc_ajax, name='free_space'),
    url(r'^ajax/remote_samples_list/$', remote_samples_list_ajax, name='remote_samples_list'),
    url(r'^ajax/check_samplesheet/$', check_samplesheet_ajax, name='check_samplesheet'),
    url(r'^run_deseq/(?P<pipeline>.*)/$', AnalysisDeseqView.as_view(), name='run_deseq'),
    url(r'^ajax/delete_analysis/$', DeleteAnalysisView.as_view(), name='delete_analysis'),
    url(r'^analysis_details/(?P<pk>[0-9]+)/$', AnalysisDetailsView.as_view(), name='analysis_details'),
    url(r'^e_learning/$', Elearning.as_view(), name='e_learning'),
    url(r'^user_datasets/$', UserDatasets.as_view(), name='user_datasets'),
    url(r'^chanalysis/$', AnalysisChoice.as_view(), name='choice_analysis'),
    url(r'^analysis/(?P<pipeline>Transcriptome.*)/$', AnalysisTranscriptomeView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>Demultiplexing.*)/$', AnalysisDemultiplexingView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>Single-cell RNA Cell Ranger.*)/$', AnalysisSinglecellView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>ATAC-Seq.*)/$', AnalysisAtacSeqView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>ChIP-Seq.*)/$', AnalysisChipSeqView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>Ribo-Seq.*)/$', AnalysisRiboSeqView.as_view(), name='analysis'),
    url(r'^analysis/(?P<pipeline>DESeq2.*)/$', AnalysisDESeqFromCountsMatrixView.as_view(), name='analysis'),
    url(r'^submit_analysis/(?P<pipeline>.*)/$', AnalysisSubmitView.as_view(), name='submit_analysis'),
    url(r'^temp/$', temp, name='temp'),
    url(r'^test/$', test, name='test'),
    url(r'^stest/$', stest, name='stest'),
    url(r'^upload_help/$', upload_help, name='upload_help'),
    url(r'^no_results/$', no_results, name='no_resutls'),
    url(r'^run_failed/$', run_failed, name=''),
    url(r'^demultiplexing_results/$', demultiplexing_results, name='demultiplexing_results'),
    url(r'^atacseq_results/$', atacseq_results, name='atacseq_results'),
    url(r'^chipseq_results/$', chipseq_results, name='chipseq_results'),
    #url(r'^$', UserDatasets.as_view(), name='user_datasets'),
    url(r'^$', Elearning.as_view(), name='e_learning'),
    url(r'^upfolder/$', UploadFolder.as_view(), name='upfolder'),
    url(r'^upload_progress/$', upload_progress, name="upload-progress"),
    url(r'^ajax/analysis_progress/$', analysis_progress_ajax.as_view(), name="analysis_progress"),
]

utap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views
from filebrowser.sites import site

from analysis.backend.forms.forms_base import LoginForm
from analysis.backend.settings import BBCU_INTERNAL, INSTITUTE_NAME, DEMO_SITE, UTAP_VERSION

urlpatterns = [
    url(r'', include('analysis.backend.urls')),
    url('^', include('django.contrib.auth.urls')),
    # url(r'^flowjs/', include('flowjs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},
        name='login'),
    url(r'^user_login/$', views.login,
        {'template_name': 'login.html', 'extra_context': {'bbcu_internal': BBCU_INTERNAL, 'institute_name': INSTITUTE_NAME, 'demosite': DEMO_SITE, 'version': UTAP_VERSION}}, name='user_login'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
]

templates/login.html
{% include "analysis/navigation_bar.html" with user=user %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

{% block content %}

{% for message in messages %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}

{% if form.errors %}
    {{ form.errors }}
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}


<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            {% if bbcu_internal %}
                <p align="center"><b>Please login with your Weizmann account username and password </b></p>
            {% else %}
                <p align="center"><b>UTAP - ngs pipelines hosted on {{ institute_name }} server</b></p>


            {% endif %}
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'user_login' %}">
                        {% csrf_token %}
                        <p class="bs-component">
                        <table>
                            {% if demosite %}
                            <tr>
                                <td>For demo site:</td>
                            </tr>
                            <tr>
                                <td>username: testuser</td>
                                <td>, password: utap1234</td>
                            </tr>
                            <tr><td><br></td></tr>
                            {% endif %}
                            <tr>
                                <td>{{ form.username.label_tag }}</td>
                                <td>{{ form.username }}</td>
                            </tr>
                            <tr>
                                <td>{{ form.password.label_tag }}</td>
                                <td>{{ form.password }}</td>
                            </tr>
                        </table>
                        </p>
                        <p class="bs-component">
                        <center>
                            <input class="btn btn-success btn-sm" type="submit" value="login"/>
                        </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
        </div>
        {% if not bbcu_internal %}
        <div class="row">

            <div class="col-md-4 col-md-offset-4">
                <center>
                    <p class="bs-component">
                    {% if demosite %}
                    <button class="btn btn-danger navbar-btn" onclick="alert('Cannot signup in demo site')">Sign Up</button><br>
                    <a onclick="alert('Cannot signup in demo site')">forgot password ?</a>
                    {% else %}
                    <button class="btn btn-danger navbar-btn" onclick="location.href='{% url 'analysis:signup' %}'">Sign Up</button><br>
                    <a href="{% url 'password_reset' %}">forgot password ?</a>
                    {% endif %}
                    </p>
                </center>
            </div>
        {% endif %}
        </div>
        </div>
    </div>
</div>

{% endblock %}


{% block javascript %}

<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>
{% endblock %}

</html>